/**
 * Created by looper on 2017/8/28.
 */
export const LOGIN = 'LOGIN';
export const LOGE_OUT = 'LOGE_OUT';
export const LOGE_ERROR = 'LOGE_ERROR';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';

export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';
export const FETCH_HOME_DATA_FAILURE = 'FETCH_HOME_DATA_FAILURE';
export const FETCH_HOME_DATA_REQUEST = 'FETCH_HOME_DATA_REQUEST';
export const FETCH_HOME_MORE_DATA_SUCCESS = 'FETCH_HOME_MORE_DATA_SUCCESS';
export const FETCH_HOME_MORE_DATA_REQUEST = 'FETCH_HOME_MORE_DATA_REQUEST';
export const FETCH_HOME_MORE_DATA_FAILURE = 'FETCH_HOME_MORE_DATA_FAILURE';

export const FETCH_COMMENT_DATA_SUCCESS = 'FETCH_COMMENT_DATA_SUCCESS';
export const FETCH_COMMENT_DATA_FAILURE = 'FETCH_COMMENT_DATA_FAILURE';
export const FETCH_COMMENT_DATA_REQUEST = 'FETCH_COMMENT_DATA_REQUEST';
export const FETCH_COMMENT_MORE_DATA_SUCCESS = 'FETCH_COMMENT_MORE_DATA_SUCCESS';
export const FETCH_COMMENT_MORE_DATA_REQUEST = 'FETCH_COMMENT_MORE_DATA_REQUEST';
export const FETCH_COMMENT_MORE_DATA_END = 'FETCH_COMMENT_MORE_DATA_END';
export const FETCH_COMMENT_MORE_DATA_FAILURE = 'FETCH_COMMENT_MORE_DATA_FAILURE';

export const FETCH_USER_GROUP_SUCCESS = 'FETCH_USER_GROUP_SUCCESS';
export const FETCH_USER_GROUP_FAILURE = 'FETCH_USER_GROUP_FAILURE';
